#!/usr/bin/env python3
"""
Canada Census Division (CD) geometry for the Canada county-equivalent BiCRS map.

Source: StatCan 2021 Cartographic Boundary File for Census divisions, fetched as GeoJSON
        (WGS84) from the StatCan ArcGIS service -> data/geo/ca_raw/cd_boundary.geojson
        (see download_raw.sh). 293 census divisions (the Canadian equivalent of US counties).

Output:
  data/geo/geometry_ca_cd.js     window.GEO_CA_CD (FeatureCollection; file:// safe)
  data/geo/ca_cd.json            same features, for the engine (point-in-polygon, basin overlap)

CDs are simplified (Douglas-Peucker) and rounded to 3 dp (~110 m). Properties:
  id       = "CA-{CDUID}"   (4-digit CDUID, e.g. CA-4806)
  name     = CD name (whitespace-normalised, e.g. "Division No. 6")
  prov     = province/territory 2-letter code (e.g. AB)  [US "state" analogue]
  cduid    = 4-digit CDUID
  area_km2 = land area (StatCan LANDAREA, km^2), used for feedstock density
  centroid = [lon, lat] area-weighted centroid of the largest ring
"""
import json
import os
import re

from build_cd_common import PRUID_TO_ABBR, simplify_ring, ring_area_centroid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEO = os.path.join(ROOT, "data", "geo")
SRC = os.path.join(GEO, "ca_raw", "cd_boundary.geojson")

COORD_DP = 3
SIMPLIFY_TOL = 0.006   # ~600 m


def process_geometry(geom):
    """Simplify a GeoJSON Polygon/MultiPolygon; return (geometry, centroid) or (None, None)."""
    t = geom["type"]
    if t == "Polygon":
        polys = [geom["coordinates"]]
    elif t == "MultiPolygon":
        polys = geom["coordinates"]
    else:
        return None, None

    new_polys = []
    best_area, best_centroid = -1.0, None
    for poly in polys:
        new_rings = []
        for ri, ring in enumerate(poly):
            sr = simplify_ring([list(pt) for pt in ring], SIMPLIFY_TOL, COORD_DP)
            if len(sr) >= 4:
                new_rings.append(sr)
                if ri == 0:
                    area, c = ring_area_centroid(sr)
                    if abs(area) > best_area:
                        best_area, best_centroid = abs(area), c
        if new_rings:
            new_polys.append(new_rings)

    if not new_polys:
        return None, None
    if len(new_polys) == 1:
        return {"type": "Polygon", "coordinates": new_polys[0]}, best_centroid
    return {"type": "MultiPolygon", "coordinates": new_polys}, best_centroid


def main():
    src = json.load(open(SRC))
    features = []
    skipped = 0
    for f in src["features"]:
        p = f["properties"]
        cduid = str(p["CDUID"])
        prov = PRUID_TO_ABBR.get(str(p["PRUID"]), str(p["PRUID"]))
        name = re.sub(r"\s+", " ", (p.get("CDNAME") or "").strip())
        geom, centroid = process_geometry(f["geometry"])
        if not geom or centroid is None:
            skipped += 1
            continue
        features.append({
            "type": "Feature",
            "properties": {
                "id": "CA-" + cduid,
                "name": name,
                "prov": prov,
                "cduid": cduid,
                "area_km2": round((p.get("LANDAREA") or 0.0), 1),
                "centroid": [round(centroid[0], COORD_DP), round(centroid[1], COORD_DP)],
            },
            "geometry": geom,
        })

    fc = {"type": "FeatureCollection", "features": features}

    out_js = os.path.join(GEO, "geometry_ca_cd.js")
    with open(out_js, "w") as f:
        f.write("// Auto-generated by scripts/ca/build_cd_geo.py — Canada CD geometry (StatCan 2021 CBF).\n")
        f.write("window.GEO_CA_CD = " + json.dumps(fc, separators=(",", ":")) + ";\n")

    out_json = os.path.join(GEO, "ca_cd.json")
    with open(out_json, "w") as f:
        json.dump(fc, f, separators=(",", ":"))

    print(f"census divisions: {len(features)} (skipped {skipped})")
    print(f"wrote {out_js} ({os.path.getsize(out_js):,} bytes)")
    print(f"wrote {out_json} ({os.path.getsize(out_json):,} bytes)")


if __name__ == "__main__":
    main()
