#!/usr/bin/env python3
"""
Canadian geologic CO2 storage-basin polygons for the CD-level BiCRS map.

Canada has no NATCARB/CO2StoP-style open polygon atlas, so these are CURATED simplified
extents of the basins that actually host (or are appraised for) deep saline / depleted-
reservoir CO2 storage. The dominant one by far is the Western Canada Sedimentary Basin
(WCSB) underlying Alberta, much of Saskatchewan, NE British Columbia and SW Manitoba — a
world-class storage resource that already hosts Quest, ACTL, Aquistore and the Weyburn EOR
complex. The Williston Basin (SE Saskatchewan / SW Manitoba, continuous into the US) is also
included. Like the US scope, a CD whose centroid falls inside a basin has storage on-site;
otherwise distance is measured to the nearest basin boundary AND nearest CCS project.

Extents are first-order (province-scale) and meant for screening, not site appraisal.

Output:
  data/geo/geometry_ca_basins.js      window.GEO_CA_BASINS (FeatureCollection; file:// safe)
  data/processed/storage_ca_basins.json   polygons + bbox for the engine (point-in / distance)
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEO = os.path.join(ROOT, "data", "geo")
PROC = os.path.join(ROOT, "data", "geo", "..", "processed")
PROC = os.path.normpath(PROC)

# Curated simplified basin outlines (lon, lat rings). Confidence "high" — these are
# established, appraised storage fairways (matches the global tool's grading for Canada).
BASINS = [
    {
        "name": "Western Canada Sedimentary Basin (WCSB)",
        "partnership": "AB/SK/BC/MB deep saline & depleted-reservoir fairway",
        "confidence": "high",
        "ring": [
            [-120.2, 56.2], [-116.0, 58.6], [-111.5, 58.8], [-110.0, 58.5],
            [-109.8, 55.0], [-108.0, 53.5], [-104.5, 51.5], [-101.4, 49.6],
            [-101.4, 49.0], [-110.0, 49.0], [-114.1, 49.0], [-114.6, 50.6],
            [-116.3, 52.2], [-118.6, 54.2], [-120.2, 56.2],
        ],
    },
    {
        "name": "Williston Basin (Canadian portion)",
        "partnership": "SE Saskatchewan / SW Manitoba (continuous into US)",
        "confidence": "high",
        "ring": [
            [-106.2, 49.0], [-100.8, 49.0], [-100.4, 50.4], [-102.6, 50.2],
            [-105.2, 49.9], [-106.2, 49.4], [-106.2, 49.0],
        ],
    },
]


def bbox_of(ring):
    xs = [p[0] for p in ring]
    ys = [p[1] for p in ring]
    return [min(xs), min(ys), max(xs), max(ys)]


def centroid_of(ring):
    a = cx = cy = 0.0
    r = ring if ring[0] == ring[-1] else ring + [ring[0]]
    for i in range(len(r) - 1):
        x0, y0 = r[i]
        x1, y1 = r[i + 1]
        cross = x0 * y1 - x1 * y0
        a += cross
        cx += (x0 + x1) * cross
        cy += (y0 + y1) * cross
    a *= 0.5
    if a == 0:
        n = len(r) - 1
        return [sum(p[0] for p in r[:-1]) / n, sum(p[1] for p in r[:-1]) / n]
    return [round(cx / (6 * a), 3), round(cy / (6 * a), 3)]


def main():
    feats, engine = [], []
    for b in BASINS:
        ring = [[round(x, 3), round(y, 3)] for x, y in b["ring"]]
        if ring[0] != ring[-1]:
            ring.append(ring[0])
        geom = {"type": "Polygon", "coordinates": [ring]}
        cent = centroid_of(ring)
        props = {
            "name": b["name"],
            "partnership": b["partnership"],
            "storage_type": "saline/depleted reservoir",
            "confidence": b["confidence"],
            "centroid": cent,
        }
        feats.append({"type": "Feature", "properties": props, "geometry": geom})
        engine.append({"name": b["name"], "confidence": b["confidence"],
                       "bbox": bbox_of(ring), "centroid": cent, "geometry": geom})

    fc = {"type": "FeatureCollection", "features": feats}
    out_js = os.path.join(GEO, "geometry_ca_basins.js")
    with open(out_js, "w") as f:
        f.write("// Auto-generated by scripts/ca/build_basin_geo.py — curated Canadian storage basins.\n")
        f.write("window.GEO_CA_BASINS = " + json.dumps(fc, separators=(",", ":")) + ";\n")

    out_json = os.path.join(PROC, "storage_ca_basins.json")
    with open(out_json, "w") as f:
        json.dump(engine, f, separators=(",", ":"))

    print(f"basins: {len(feats)} curated Canadian storage basins")
    print(f"wrote {out_js} ({os.path.getsize(out_js):,} bytes)")
    print(f"wrote {out_json} ({os.path.getsize(out_json):,} bytes)")


if __name__ == "__main__":
    main()
