#!/usr/bin/env python3
"""Bundle Canada CD datasets into src/data_bundle_ca.js (window globals; file:// safe).

Mirrors bundle_us.py: feedstocks slimmed to per-stream values; recommendations' templated
`ranked` replaced by `ranked_keys` (frontend rebuilds pros/cons from window.CA_PATHWAY_PROFILE).
Geometry (CDs + basins) is bundled separately by build_cd_geo.py / build_basin_geo.py.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # scripts/
from engine_core import PATHWAYS, PATHWAY_PROFILE

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROC = os.path.join(ROOT, "data", "processed")
OUT = os.path.join(ROOT, "src", "data_bundle_ca.js")


def load(name):
    with open(os.path.join(PROC, name)) as f:
        return json.load(f)


def v(rec, key):
    x = rec.get(key)
    return (x or {}).get("value", 0) if isinstance(x, dict) else 0


def slim_feedstocks(feeds):
    out = []
    for r in feeds:
        out.append({
            "id": r["id"], "name": r["name"], "prov": r["prov"], "cduid": r["cduid"],
            "area_km2": r["area_km2"], "centroid": r["centroid"],
            "ag": round(v(r, "ag_residues_odt_mt"), 4),
            "forestry": round(v(r, "forestry_residues_odt_mt"), 4),
            "msw": round(v(r, "msw_total_mt"), 4),
            "manure": round(v(r, "animal_manure_odt_mt"), 4),
            "wwtp": round(v(r, "human_wwtp_odt_mt"), 4),
            "biofrac": v(r, "msw_biogenic_frac") or 0.55,
            "nutrient_status": r["nutrient_status"],
            "dominant_feedstock": r["dominant_feedstock"],
        })
    return out


def slim_recs(recs):
    out = []
    for r in recs:
        r = dict(r)
        r["ranked_keys"] = [{"k": x["key"], "b": x["badge"]} for x in r.get("ranked", [])]
        r.pop("ranked", None)
        out.append(r)
    return out


PROFILE = {k: {"label": PATHWAYS[k]["label"],
               "eff": PATHWAYS[k]["cdr_efficiency"],
               "cost": PATHWAYS[k]["cost_band"],
               "needs_storage": PATHWAYS[k]["needs_geologic_storage"],
               "pros": PATHWAY_PROFILE[k]["pros"],
               "cons": PATHWAY_PROFILE[k]["cons"]}
           for k in PATHWAYS}

bundle = {
    "CA_FEEDSTOCKS": slim_feedstocks(load("feedstocks_ca_cd.json")),
    "CA_RECOMMENDATIONS": slim_recs(load("recommendations_ca.json")),
    "CA_FACILITIES": load("facilities_ca_detailed.json"),
    "CA_WELLS": load("wells_ca.json"),
    "CA_WWTPS": load("wwtps_ca.json"),
    "CA_TRANSPORT": load("transport_ca.json"),
    "CA_PATHWAY_PROFILE": PROFILE,
}

with open(OUT, "w") as f:
    f.write("// Auto-generated by scripts/ca/bundle_ca.py — do not edit by hand.\n")
    for k, val in bundle.items():
        f.write(f"window.{k} = " + json.dumps(val, separators=(",", ":"), ensure_ascii=False) + ";\n")

print("bundled:", {k: (len(v) if isinstance(v, (list, dict)) else 1) for k, v in bundle.items()})
print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")
