#!/usr/bin/env python3
"""
US wildfire-fuels-treatment residue stream (to_do item 2, phase 3).

Adds the woody biomass generated by hazardous-fuel-reduction treatments — thinning, biomass
removal, machine-pile (and pile-burn) slash, chipping — that is today largely **pile-burned or
left on site**, especially on fire-prone federal land in the interior West (the Sierra Nevada,
etc.) where there is little commercial logging. The commercial forestry layer (BT23 logging
residue, FIA-allocated) misses this because it keys off harvest; this stream is a separate,
largely-additional feedstock with a distinct (policy-driven, seasonal, dispersed) supply story.

Source: USFS **FACTS Hazardous Fuel Treatments** (EDW ArcGIS, layer 15 "Hazardous Fuel Treatment
Reduction: Polygon"). We take treatments COMPLETED in a recent multi-year window and keep only the
biomass-*removing* treatment types (broadcast/jackpot/fire-use burns consume biomass on site and are
excluded). Per-treatment removable oven-dry biomass = acres × a per-type yield factor (conservative,
mid-range of the fuels-treatment bioenergy literature — Evans & Finkral, NREL/CBI Sierra studies),
annualized over the window for a sustained Mt-odt/yr rate, and allocated to the county the treatment
sits in (treatment polygon's representative vertex → county, point-in-polygon).

Writes: data/processed/fuels_residues_us.json  ->  {fips: Mt odt/yr}
Consumed by build_county_feedstocks.py, which folds it into the forestry stream (so it drives
dominant_feedstock + CDR) while keeping it tagged separately for provenance/display.
"""
import json
import os
import sys
import time
import urllib.parse
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # scripts/
from engine_core import _point_in_geometry  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RAW = os.path.join(ROOT, "data", "geo", "us_raw", "facts")
COUNTIES = os.path.join(ROOT, "data", "geo", "us_counties.json")
OUT = os.path.join(ROOT, "data", "processed", "fuels_residues_us.json")

SERVICE = ("https://apps.fs.usda.gov/arcx/rest/services/EDW/"
           "EDW_HazardousFuelsTreatments_01/MapServer/15/query")
FY_LO, FY_HI = 2018, 2024            # completed-treatment window
N_YEARS = FY_HI - FY_LO + 1
PAGE = 2000

# Removable (haulable) treatment types -> oven-dry tons of removable biomass per treated acre.
# Conservative, mid-range of the western fuels-treatment literature; documented in METHODOLOGY.
# Excluded entirely: Broadcast Burn / Fire Use / Jackpot Burn (combusted on site), Lop and Scatter /
# Mastication / Crushing / Mowing (left dispersed on site, not a collectable stream), Grazing/Chemical.
YIELD_ODT_PER_ACRE = {
    "Thinning": 12.0,
    "Biomass Removal": 10.0,
    "Machine Pile": 8.0,
    "Machine Pile Burn": 8.0,     # piled slash currently burned — divertible to BiCRS
    "Chipping": 6.0,
}
UA = {"User-Agent": "BiCRS-Atlas/1.0 (research; wildfire-fuels residue)"}


def fetch_pages():
    """Paginate FACTS layer 15 (removable types, completed in window), caching each page.
    Returns list of (lon, lat, acres, treatment_type)."""
    os.makedirs(RAW, exist_ok=True)
    types = ",".join("'%s'" % t for t in YIELD_ODT_PER_ACRE)
    where = (f"fiscal_year_completed>={FY_LO} AND fiscal_year_completed<={FY_HI} "
             f"AND treatment_type IN ({types})")
    recs = []
    offset = 0
    page_idx = 0
    while True:
        dest = os.path.join(RAW, f"haz_{FY_LO}_{FY_HI}_pg{page_idx:04d}.json")
        if os.path.exists(dest) and os.path.getsize(dest) > 0:
            txt = open(dest, encoding="utf-8").read()
        else:
            params = {
                "where": where, "outFields": "treatment_type,gis_acres",
                "returnGeometry": "true", "maxAllowableOffset": "0.02",
                "geometryPrecision": "4", "resultRecordCount": PAGE,
                "resultOffset": offset, "f": "json",
            }
            txt = _get(SERVICE + "?" + urllib.parse.urlencode(params), dest)
            if not txt:
                break
        try:
            d = json.loads(txt)
        except ValueError:
            break
        feats = d.get("features", [])
        for f in feats:
            a = f.get("attributes", {})
            acres = a.get("gis_acres")
            tt = a.get("treatment_type")
            g = f.get("geometry") or {}
            rings = g.get("rings") or []
            if not acres or not rings or not rings[0]:
                continue
            lon, lat = rings[0][0][0], rings[0][0][1]   # representative vertex (small polygons)
            recs.append((lon, lat, float(acres), tt))
        print(f"  page {page_idx}: {len(feats)} features (cum {len(recs)})")
        if not d.get("exceededTransferLimit") or not feats:
            break
        offset += PAGE
        page_idx += 1
    return recs


def _get(url, dest):
    for attempt in range(3):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=120) as r:
                txt = r.read().decode("utf-8", "replace")
            with open(dest, "w", encoding="utf-8") as f:
                f.write(txt)
            return txt
        except Exception as e:  # noqa: BLE001
            if attempt == 2:
                print(f"    ! failed {url[:80]}: {e}")
                return ""
            time.sleep(3)
    return ""


def bbox_of(geom):
    xs, ys = [], []

    def walk(c):
        if isinstance(c[0], (int, float)):
            xs.append(c[0]); ys.append(c[1])
        else:
            for x in c:
                walk(x)
    walk(geom["coordinates"])
    return (min(xs), min(ys), max(xs), max(ys))


class CountyGrid:
    """Coarse 1°×1° grid index of county bounding boxes for fast point-in-county lookup."""
    def __init__(self, counties):
        self.cells = {}
        self.counties = []
        for c in counties:
            fips = c["properties"]["fips"]
            geom = c["geometry"]
            bb = bbox_of(geom)
            idx = len(self.counties)
            self.counties.append((fips, geom, bb))
            x0, y0, x1, y1 = bb
            for gx in range(int(x0 // 1), int(x1 // 1) + 1):
                for gy in range(int(y0 // 1), int(y1 // 1) + 1):
                    self.cells.setdefault((gx, gy), []).append(idx)

    def fips_of(self, lon, lat):
        for idx in self.cells.get((int(lon // 1), int(lat // 1)), ()):
            fips, geom, (x0, y0, x1, y1) = self.counties[idx]
            if x0 <= lon <= x1 and y0 <= lat <= y1 and _point_in_geometry(lon, lat, geom):
                return fips
        return None


def main():
    recs = fetch_pages()
    print(f"FACTS: {len(recs)} removable fuels-treatment records (FY{FY_LO}-{FY_HI})")
    counties = json.load(open(COUNTIES))["features"]
    grid = CountyGrid(counties)

    by_fips = {}
    unmatched = 0
    for lon, lat, acres, tt in recs:
        fips = grid.fips_of(lon, lat)
        if fips is None:
            unmatched += 1
            continue
        odt = acres * YIELD_ODT_PER_ACRE.get(tt, 0.0) / N_YEARS   # annual oven-dry tons
        by_fips[fips] = by_fips.get(fips, 0.0) + odt

    out = {f: round(v / 1e6, 6) for f, v in by_fips.items() if v > 0}   # Mt odt/yr
    with open(OUT, "w") as f:
        json.dump(out, f)

    tot = sum(out.values())
    top = sorted(out.items(), key=lambda kv: -kv[1])[:8]
    fips2name = {c["properties"]["fips"]: (c["properties"]["name"], c["properties"]["state"])
                 for c in counties}
    print(f"wrote {len(out)} county fuels-residue records -> {OUT}")
    print(f"  total {tot:.2f} Mt odt/yr | {unmatched} unmatched centroids")
    print("  top counties:")
    for fp, v in top:
        nm, st = fips2name.get(fp, ("?", "?"))
        print(f"    {nm}, {st}: {v:.3f} Mt odt/yr")


if __name__ == "__main__":
    main()
