#!/usr/bin/env python3
"""
EU geologic CO2 storage formations for the NUTS-2 BiCRS map.

Source: CO2StoP (JRC/SETIS) open-format KML — StorageUnits_March13.kml: the units of
assessment (saline aquifers + hydrocarbon fields) as WGS84 polygons. The European
equivalent of the US NATCARB basin polygons.

Output:
  data/geo/geometry_eu_storage.js      window.GEO_EU_STORAGE (FeatureCollection; file:// safe)
  data/processed/storage_eu_formations.json   polygons + bbox for the engine (point-in / distance)
"""
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/../us")
from build_county_geo import _dp, _ring_area_centroid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEO = os.path.join(ROOT, "data", "geo")
PROC = os.path.join(ROOT, "data", "processed")
KML = os.path.join(GEO, "eu_raw", "co2stop", "CO2JRC_OpenFormats",
                   "CO2Stop_Polygons Data", "StorageUnits_March13.kml")

COORD_DP = 3
TOL = 0.01          # ~1 km Douglas-Peucker tolerance
MIN_AREA_DEG2 = 0.003  # drop tiny slivers


def local(tag):
    return tag.rsplit("}", 1)[-1]


def parse_coords(text):
    """KML 'lon,lat,alt lon,lat,alt ...' -> [[lon,lat], ...]."""
    pts = []
    for tok in text.split():
        parts = tok.split(",")
        if len(parts) >= 2:
            try:
                pts.append([float(parts[0]), float(parts[1])])
            except ValueError:
                pass
    return pts


def simplify_ring(ring):
    if len(ring) > 4:
        ring = _dp(ring, TOL)
    out, last = [], None
    for x, y in ring:
        pt = [round(x, COORD_DP), round(y, COORD_DP)]
        if pt != last:
            out.append(pt)
        last = pt
    if len(out) < 4:
        return None
    if out[0] != out[-1]:
        out.append(out[0])
    return out


def polygon_rings(poly_el):
    """Extract [outer, inner...] coordinate rings from a KML <Polygon>."""
    rings = []
    for boundary in poly_el:
        btag = local(boundary.tag)
        if btag not in ("outerBoundaryIs", "innerBoundaryIs"):
            continue
        coords_el = [e for e in boundary.iter() if local(e.tag) == "coordinates"]
        if coords_el and coords_el[0].text:
            ring = parse_coords(coords_el[0].text)
            sr = simplify_ring(ring)
            if sr:
                rings.append((btag, sr))
    outer = [r for t, r in rings if t == "outerBoundaryIs"]
    inner = [r for t, r in rings if t == "innerBoundaryIs"]
    return outer, inner


def bbox_centroid(geom):
    xs, ys = [], []

    def walk(c):
        if isinstance(c[0], (int, float)):
            xs.append(c[0]); ys.append(c[1])
        else:
            for x in c:
                walk(x)
    walk(geom["coordinates"])
    return [min(xs), min(ys), max(xs), max(ys)]


def main():
    tree = ET.parse(KML)
    root = tree.getroot()
    placemarks = [e for e in root.iter() if local(e.tag) == "Placemark"]

    feats, engine = [], []
    for pm in placemarks:
        name = next((e.text for e in pm.iter()
                     if local(e.tag) == "name" and e.text), "Storage unit")
        fields = {e.attrib.get("name"): e.text
                  for e in pm.iter() if local(e.tag) == "SimpleData"}
        country = fields.get("COUNTRY", "")

        # Collect all polygons in the placemark (a unit may be a MultiGeometry).
        mp = []
        best_area, best_centroid = -1.0, None
        for poly_el in [e for e in pm.iter() if local(e.tag) == "Polygon"]:
            outer, inner = polygon_rings(poly_el)
            if not outer:
                continue
            rings = [outer[0]] + inner
            a, c = _ring_area_centroid(outer[0])
            if abs(a) < MIN_AREA_DEG2:
                continue
            mp.append(rings)
            if abs(a) > best_area:
                best_area, best_centroid = abs(a), c
        if not mp:
            continue
        geom = ({"type": "Polygon", "coordinates": mp[0]} if len(mp) == 1
                else {"type": "MultiPolygon", "coordinates": mp})
        props = {
            "name": (name or "Storage unit").strip(),
            "country": country,
            "storage_type": "saline/HC",
            "confidence": "assessed",
            "centroid": [round(best_centroid[0], COORD_DP), round(best_centroid[1], COORD_DP)],
        }
        feats.append({"type": "Feature", "properties": props, "geometry": geom})
        engine.append({"name": props["name"], "centroid": props["centroid"],
                       "bbox": bbox_centroid(geom), "geometry": geom})

    fc = {"type": "FeatureCollection", "features": feats}
    out_js = os.path.join(GEO, "geometry_eu_storage.js")
    with open(out_js, "w") as f:
        f.write("// Auto-generated by scripts/eu/build_storage_geo.py — CO2StoP storage units (JRC).\n")
        f.write("window.GEO_EU_STORAGE = " + json.dumps(fc, separators=(",", ":"), ensure_ascii=False) + ";\n")
    out_json = os.path.join(PROC, "storage_eu_formations.json")
    with open(out_json, "w") as f:
        json.dump(engine, f, separators=(",", ":"), ensure_ascii=False)

    print(f"storage formations: {len(feats)}")
    print(f"wrote {out_js} ({os.path.getsize(out_js):,} bytes)")
    print(f"wrote {out_json} ({os.path.getsize(out_json):,} bytes)")


if __name__ == "__main__":
    main()
