#!/usr/bin/env python3
"""
EU NUTS-2 geometry for the European BiCRS map.

Source: Eurostat GISCO NUTS 2021, NUTS_RG_20M_2021_4326_LEVL_2.geojson (WGS84).
Filter to EU-27 + UK + Norway. Simplify (Douglas-Peucker) + round to 3 dp.

Output:
  data/geo/geometry_eu_nuts.js   window.GEO_EU_NUTS (FeatureCollection; file:// safe)
  data/geo/eu_nuts.json          same features, for the engine (point-in-polygon, basin overlap)

Properties per region:
  id       = "EU-{NUTS_ID}"  (e.g. EU-DE21)
  name     = region name (NAME_LATN)
  country  = ISO3 (so engine manure_ad_preferred / region_country fire correctly)
  cntr     = 2-letter country code
  area_km2 = planar-ish area from the largest ring (deg^2 -> km^2 approx at region latitude)
  centroid = [lon, lat] area-weighted centroid of the largest ring
"""
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/../us")  # reuse DP helpers
from build_county_geo import _dp, _ring_area_centroid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEO = os.path.join(ROOT, "data", "geo")
SRC = os.path.join(GEO, "eu_raw", "nuts2.geojson")

COORD_DP = 3
SIMPLIFY_TOL = 0.01  # ~1 km; NUTS-2 regions are large, coastlines need not be fine

# EU-27 + UK + Norway (2-letter CNTR_CODE). EL = Greece, UK = United Kingdom.
EU27 = {"AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "EL", "ES", "FI", "FR",
        "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PL", "PT", "RO",
        "SE", "SI", "SK"}
KEEP = EU27 | {"UK", "NO"}


def simplify_ring(ring):
    if len(ring) > 4:
        ring = _dp(ring, SIMPLIFY_TOL)
    out, last = [], None
    for x, y in ring:
        pt = [round(x, COORD_DP), round(y, COORD_DP)]
        if pt != last:
            out.append(pt)
        last = pt
    if len(out) < 4:
        return None
    if out[0] != out[-1]:
        out.append(out[0])
    return out


def process_geometry(geom):
    t = geom["type"]
    polys = [geom["coordinates"]] if t == "Polygon" else (
        geom["coordinates"] if t == "MultiPolygon" else None)
    if polys is None:
        return None, None, None
    new_polys = []
    best_area, best_centroid = -1.0, None
    for poly in polys:
        rings = []
        for ri, ring in enumerate(poly):
            sr = simplify_ring([list(p) for p in ring])
            if sr and len(sr) >= 4:
                rings.append(sr)
                if ri == 0:
                    a, c = _ring_area_centroid(sr)
                    if abs(a) > best_area:
                        best_area, best_centroid = abs(a), c
        if rings:
            new_polys.append(rings)
    if not new_polys:
        return None, None, None
    geom_out = ({"type": "Polygon", "coordinates": new_polys[0]} if len(new_polys) == 1
                else {"type": "MultiPolygon", "coordinates": new_polys})
    # deg^2 -> km^2 at the region's latitude (cos correction)
    lat = best_centroid[1] if best_centroid else 50.0
    km_per_deg_lat = 111.0
    km_per_deg_lon = 111.0 * math.cos(math.radians(lat))
    area_km2 = round(best_area * km_per_deg_lat * km_per_deg_lon, 1)
    return geom_out, best_centroid, area_km2


def main():
    gj = json.load(open(SRC))
    feats = []
    for f in gj["features"]:
        p = f["properties"]
        if p.get("CNTR_CODE") not in KEEP:
            continue
        geom, centroid, area = process_geometry(f["geometry"])
        if not geom:
            continue
        nuts = p["NUTS_ID"]
        feats.append({
            "type": "Feature",
            "properties": {
                "id": "EU-" + nuts,
                "name": p.get("NAME_LATN") or p.get("NUTS_NAME") or nuts,
                "country": p.get("ISO3_CODE"),
                "cntr": p.get("CNTR_CODE"),
                "nuts_id": nuts,
                "area_km2": area,
                "centroid": [round(centroid[0], COORD_DP), round(centroid[1], COORD_DP)],
            },
            "geometry": geom,
        })
    feats.sort(key=lambda x: x["properties"]["nuts_id"])
    fc = {"type": "FeatureCollection", "features": feats}

    out_js = os.path.join(GEO, "geometry_eu_nuts.js")
    with open(out_js, "w") as f:
        f.write("// Auto-generated by scripts/eu/build_nuts_geo.py — EU NUTS-2 geometry (GISCO 2021, 20M).\n")
        f.write("window.GEO_EU_NUTS = " + json.dumps(fc, separators=(",", ":"), ensure_ascii=False) + ";\n")
    out_json = os.path.join(GEO, "eu_nuts.json")
    with open(out_json, "w") as f:
        json.dump(fc, f, separators=(",", ":"), ensure_ascii=False)

    from collections import Counter
    cc = Counter(x["properties"]["cntr"] for x in feats)
    print(f"NUTS-2 regions: {len(feats)} across {len(cc)} countries")
    print(f"wrote {out_js} ({os.path.getsize(out_js):,} bytes)")
    print(f"wrote {out_json} ({os.path.getsize(out_json):,} bytes)")


if __name__ == "__main__":
    main()
