#!/usr/bin/env python3
"""Bundle EU NUTS-2 datasets into src/data_bundle_eu.js (window globals; file:// safe).

Same slimming as bundle_us.py: feedstock values only, and `ranked` -> `ranked_keys`
(the frontend rebuilds pros/cons from window.EU_PATHWAY_PROFILE). Geometry (NUTS-2 +
storage formations) is bundled separately by build_nuts_geo.py / build_storage_geo.py.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # scripts/
from engine_core import PATHWAYS, PATHWAY_PROFILE

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROC = os.path.join(ROOT, "data", "processed")
OUT = os.path.join(ROOT, "src", "data_bundle_eu.js")


def load(name):
    with open(os.path.join(PROC, name)) as f:
        return json.load(f)


def v(rec, key):
    x = rec.get(key)
    return (x or {}).get("value", 0) if isinstance(x, dict) else 0


def slim_feedstocks(feeds):
    out = []
    for r in feeds:
        out.append({
            "id": r["id"], "name": r["name"], "country": r["parent"], "cntr": r["cntr"],
            "nuts_id": r["nuts_id"], "area_km2": r["area_km2"], "centroid": r["centroid"],
            "ag": round(v(r, "ag_residues_odt_mt"), 4),
            "forestry": round(v(r, "forestry_residues_odt_mt"), 4),
            "msw": round(v(r, "msw_total_mt"), 4),
            "manure": round(v(r, "animal_manure_odt_mt"), 4),
            "wwtp": round(v(r, "human_wwtp_odt_mt"), 4),
            "biofrac": v(r, "msw_biogenic_frac") or 0.5,
            "nutrient_status": r["nutrient_status"],
            "dominant_feedstock": r["dominant_feedstock"],
        })
    return out


def slim_recs(recs):
    out = []
    for r in recs:
        r = dict(r)
        r["ranked_keys"] = [{"k": x["key"], "b": x["badge"]} for x in r.get("ranked", [])]
        r.pop("ranked", None)
        out.append(r)
    return out


PROFILE = {k: {"label": PATHWAYS[k]["label"],
               "eff": PATHWAYS[k]["cdr_efficiency"],
               "cost": PATHWAYS[k]["cost_band"],
               "needs_storage": PATHWAYS[k]["needs_geologic_storage"],
               "pros": PATHWAY_PROFILE[k]["pros"],
               "cons": PATHWAY_PROFILE[k]["cons"]}
           for k in PATHWAYS}

bundle = {
    "EU_FEEDSTOCKS": slim_feedstocks(load("feedstocks_eu_nuts.json")),
    "EU_RECOMMENDATIONS": slim_recs(load("recommendations_eu.json")),
    "EU_FACILITIES": load("facilities_eu.json"),
    "EU_STORAGE_PROJECTS": load("storage_projects_eu.json"),
    "EU_WWTPS": load("wwtps_eu.json"),
    "EU_PATHWAY_PROFILE": PROFILE,
}

with open(OUT, "w") as f:
    f.write("// Auto-generated by scripts/eu/bundle_eu.py — do not edit by hand.\n")
    for k, val in bundle.items():
        f.write(f"window.{k} = " + json.dumps(val, separators=(",", ":"), ensure_ascii=False) + ";\n")

print("bundled:", {k: (len(v) if isinstance(v, (list, dict)) else 1) for k, v in bundle.items()})
print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")
