#!/usr/bin/env python3
"""Slim country + subnational geometry and bundle as JS globals (file:// safe).

Countries use Natural Earth 1:50m. Subnational regions (US states + Canada/India/China
provinces) are drawn at admin-1 resolution for the countries we analyse sub-nationally.
Coordinates are rounded to 3 decimals (~110 m, sub-pixel at the map's max zoom).
"""
import json, os

GEO = os.path.join(os.path.dirname(__file__), "..", "data", "geo")
COORD_DP = 3  # decimal places to keep (~110 m precision)

# Countries drawn at subnational (admin-1) resolution. iso3 -> 2-letter id prefix.
SUBNATIONAL_COUNTRIES = {"CAN": "CA", "IND": "IN", "CHN": "CN"}


def round_coords(obj):
    if isinstance(obj, float):
        return round(obj, COORD_DP)
    if isinstance(obj, list):
        return [round_coords(x) for x in obj]
    return obj


def round_geometry(geom):
    geom = dict(geom)
    geom["coordinates"] = round_coords(geom["coordinates"])
    return geom


def slug(name):
    return name.replace(" ", "_").replace("/", "_")


# --- Countries (50m): keep iso_a3 + name only, rounded geometry ---
with open(os.path.join(GEO, "countries_50m.geojson")) as f:
    countries = json.load(f)

slim_countries = {"type": "FeatureCollection", "features": []}
for feat in countries["features"]:
    p = feat["properties"]
    iso = p.get("ADM0_A3") or p.get("ISO_A3") or p.get("SOV_A3")
    name = p.get("ADMIN") or p.get("SOVEREIGNT") or p.get("NAME")
    if not iso or iso == "-99":
        continue
    slim_countries["features"].append({
        "type": "Feature",
        "properties": {"iso_a3": iso, "name": name},
        "geometry": round_geometry(feat["geometry"]),
    })

# --- Subnational: US states + CAN/IND/CHN provinces, unified collection ---
subnat = {"type": "FeatureCollection", "features": []}

# US states (own source file: properties.name)
with open(os.path.join(GEO, "us_states_raw.geojson")) as f:
    us = json.load(f)
for feat in us["features"]:
    name = feat["properties"].get("name")
    subnat["features"].append({
        "type": "Feature",
        "properties": {"id": "US-" + slug(name), "name": name, "country": "USA"},
        "geometry": round_geometry(feat["geometry"]),
    })

# CAN / IND / CHN provinces (Natural Earth admin-1)
with open(os.path.join(GEO, "admin1_50m.geojson")) as f:
    admin1 = json.load(f)
counts = {}
for feat in admin1["features"]:
    p = feat["properties"]
    iso = p.get("adm0_a3")
    if iso not in SUBNATIONAL_COUNTRIES:
        continue
    name = p.get("name_en") or p.get("name")
    if not name:
        continue
    prefix = SUBNATIONAL_COUNTRIES[iso]
    subnat["features"].append({
        "type": "Feature",
        "properties": {"id": f"{prefix}-" + slug(name), "name": name, "country": iso},
        "geometry": round_geometry(feat["geometry"]),
    })
    counts[iso] = counts.get(iso, 0) + 1

out = os.path.join(GEO, "geometry.js")
with open(out, "w") as f:
    f.write("// Auto-generated by build_geo.py — country (NE 50m) + subnational (admin-1) geometry.\n")
    f.write("window.GEO_COUNTRIES = " + json.dumps(slim_countries, separators=(",", ":")) + ";\n")
    f.write("window.GEO_SUBNATIONAL = " + json.dumps(subnat, separators=(",", ":")) + ";\n")

# JSON copy of subnational geometry for the recommendation engine (point-in-polygon matching).
with open(os.path.join(GEO, "subnational.json"), "w") as f:
    json.dump(subnat, f, separators=(",", ":"))

us_n = sum(1 for x in subnat["features"] if x["properties"]["country"] == "USA")
print(f"countries: {len(slim_countries['features'])}")
print(f"subnational: {len(subnat['features'])} (US {us_n}, " +
      ", ".join(f"{k} {v}" for k, v in counts.items()) + ")")
print(f"wrote {out} ({os.path.getsize(out):,} bytes)")
