#!/usr/bin/env python3
"""Slim country + US-state geometry and bundle as JS globals (file:// safe).

Countries use Natural Earth 1:50m for finer coastlines; coordinates are rounded to 3
decimals (~110 m, sub-pixel at the map's max zoom) to keep the payload small.
"""
import json, os

GEO = os.path.join(os.path.dirname(__file__), "..", "data", "geo")
COORD_DP = 3  # decimal places to keep (~110 m precision)


def round_coords(obj):
    """Recursively round coordinate numbers in a GeoJSON geometry."""
    if isinstance(obj, float):
        return round(obj, COORD_DP)
    if isinstance(obj, list):
        return [round_coords(x) for x in obj]
    return obj


def round_geometry(geom):
    geom = dict(geom)
    geom["coordinates"] = round_coords(geom["coordinates"])
    return geom


# --- Countries (50m): keep iso_a3 + name only, rounded geometry ---
with open(os.path.join(GEO, "countries_50m.geojson")) as f:
    countries = json.load(f)

slim_countries = {"type": "FeatureCollection", "features": []}
for feat in countries["features"]:
    p = feat["properties"]
    iso = p.get("ADM0_A3") or p.get("ISO_A3") or p.get("SOV_A3")
    name = p.get("ADMIN") or p.get("SOVEREIGNT") or p.get("NAME")
    if not iso or iso == "-99":
        continue
    slim_countries["features"].append({
        "type": "Feature",
        "properties": {"iso_a3": iso, "name": name},
        "geometry": round_geometry(feat["geometry"]),
    })

# --- US states: keep name; build a stable id ---
with open(os.path.join(GEO, "us_states_raw.geojson")) as f:
    states = json.load(f)

slim_states = {"type": "FeatureCollection", "features": []}
for feat in states["features"]:
    name = feat["properties"].get("name")
    sid = "US-" + name.replace(" ", "_")
    slim_states["features"].append({
        "type": "Feature",
        "properties": {"id": sid, "name": name, "country": "USA"},
        "geometry": round_geometry(feat["geometry"]),
    })

out = os.path.join(GEO, "geometry.js")
with open(out, "w") as f:
    f.write("// Auto-generated by build_geo.py — country (NE 50m) + US-state geometry as globals.\n")
    f.write("window.GEO_COUNTRIES = " + json.dumps(slim_countries, separators=(",", ":")) + ";\n")
    f.write("window.GEO_US_STATES = " + json.dumps(slim_states, separators=(",", ":")) + ";\n")

print(f"countries: {len(slim_countries['features'])}, us_states: {len(slim_states['features'])}")
print(f"wrote {out} ({os.path.getsize(out):,} bytes)")
