#!/usr/bin/env python3
"""Slim country + US-state geometry and bundle as JS globals (file:// safe)."""
import json, os

GEO = os.path.join(os.path.dirname(__file__), "..", "data", "geo")

# --- Countries: keep iso_a3 + name only ---
with open(os.path.join(GEO, "countries_raw.geojson")) as f:
    countries = json.load(f)

slim_countries = {"type": "FeatureCollection", "features": []}
for feat in countries["features"]:
    p = feat["properties"]
    iso = p.get("ADM0_A3") or p.get("ISO_A3") or p.get("SOV_A3")
    name = p.get("ADMIN") or p.get("SOVEREIGNT") or p.get("NAME")
    if not iso or iso == "-99":
        continue
    slim_countries["features"].append({
        "type": "Feature",
        "properties": {"iso_a3": iso, "name": name},
        "geometry": feat["geometry"],
    })

# --- US states: keep name; build a stable id ---
with open(os.path.join(GEO, "us_states_raw.geojson")) as f:
    states = json.load(f)

slim_states = {"type": "FeatureCollection", "features": []}
for feat in states["features"]:
    name = feat["properties"].get("name")
    sid = "US-" + name.replace(" ", "_")
    slim_states["features"].append({
        "type": "Feature",
        "properties": {"id": sid, "name": name, "country": "USA"},
        "geometry": feat["geometry"],
    })

out = os.path.join(GEO, "geometry.js")
with open(out, "w") as f:
    f.write("// Auto-generated by build_geo.py — country + US-state geometry as globals.\n")
    f.write("window.GEO_COUNTRIES = " + json.dumps(slim_countries, separators=(",", ":")) + ";\n")
    f.write("window.GEO_US_STATES = " + json.dumps(slim_states, separators=(",", ":")) + ";\n")

print(f"countries: {len(slim_countries['features'])}, us_states: {len(slim_states['features'])}")
print(f"wrote {out} ({os.path.getsize(out):,} bytes)")
