#!/usr/bin/env python3
"""Bundle processed JSON datasets into a single JS file of window globals (file:// safe)."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROC = os.path.join(ROOT, "data", "processed")
OUT = os.path.join(ROOT, "src", "data_bundle.js")

def load(name):
    with open(os.path.join(PROC, name)) as f:
        return json.load(f)

bundle = {
    "DATA_FEEDSTOCKS": load("feedstocks.json"),
    "DATA_STORAGE": load("storage.json"),
    "DATA_FACILITIES": load("facilities.json"),
    "DATA_RECOMMENDATIONS": load("recommendations.json"),
}

with open(OUT, "w") as f:
    f.write("// Auto-generated by bundle_data.py — do not edit by hand.\n")
    for k, v in bundle.items():
        f.write(f"window.{k} = " + json.dumps(v, separators=(",", ":"), ensure_ascii=False) + ";\n")

sizes = {k: len(v) for k, v in bundle.items()}
print("bundled:", sizes)
print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")
